### ISSUE TITLE
typo and request

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager-helm#1]
Hi guys!
please fix the typo of profileConifg to profileConfig

In addition, please add load from secret option.

In addition, please add socket mode support. There is no really need to expose a public ip for that.

**Comment by emrul** [comment]
Hi @ErezWeiss - thanks for opening this issue. We will investigate these options but on socket mode we didn't support it previously because Slack did not recommend it for production use-cases (we will check to see if this has since changed).

**Comment by ErezWeiss** [comment]
> Hi @ErezWeiss - thanks for opening this issue. We will investigate these options but on socket mode we didn't support it previously because Slack did not recommend it for production use-cases (we will check to see if this has since changed).

Thanks! @emrul 
I've never seen such a recommendation, interesting. Anyway, as no other endpoint has to talk with this App except Slack itself - I guess this is the correct approach.

**Comment by emrul** [comment]
We've reviewed it internally. The guidance from Slack is as follows: 
![image](https://github.com/Twingate-Labs/tg-group-profile-manager-helm/assets/674888/b0f621b1-3c88-477f-86b8-15b493124f9b)

Also, we are wanting to list it in the App Directory in the medium term. Still, we'll investigate supporting socket-mode for users who want to try it (we use it during development).

**Comment by ErezWeiss** [comment]
Thanks! that was fast :) 
@emrul @chenbishop 
I noticed that you are testing the "values from secret", looking forward to using it.

**Comment by ErezWeiss** [comment]
@chenbishop 

this worked for me:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tg-group-profile-manager.fullname" . }}
  labels:
    {{- include "tg-group-profile-manager.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tg-group-profile-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tg-group-profile-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          resources:
            {{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.externalSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecret.name }}
          {{- else }}
          env:
            - name: TG_ACCOUNT
              value: {{ .Values.variables.twingateAccount }}
            - name: TG_API_KEY
              value: {{ .Values.variables.twingateApiKey }}
            - name: SLACK_SIGNING_SECRET
              value: {{ .Values.variables.slackSigningSecret }}
            - name: SLACK_BOT_TOKEN
              value: {{ .Values.variables.slackBotToken }}
            - name: PROFILE_CONFIG
              value: {{ .Values.variables.profileConfig | toJson | quote }}
            - name: DEPLOY_ENV
              value: {{ .Values.variables.deployEnv }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

```

**Comment by chenbishop** [comment]
@ErezWeiss Thank you very much! I will take a look the secret.

**Comment by ErezWeiss** [comment]
It worked for me. but now I just understood that it doesn't work with Okta.
I have to create my own app...

**Comment by chenbishop** [comment]
@ErezWeiss Thank you very much for your help. I have updated the helm chart (v0.1.3) to include the support for secret, see [here](https://github.com/Twingate-Labs/tg-group-profile-manager-helm/blob/gh-pages/docs/WITH_SECRET.md) for the doc. Please let me know you thought.

**Comment by ErezWeiss** [comment]
@chenbishop @emrul 
Worked great!
Last thing regarding this chart is the ports. You have to align it either to 80 or 8080 but not to use both. 
Also please add health check path. currently the alb returns 404 always...  
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
